axis_linear_x: 1       # Left Analog X
axis_linear_y: 0       # Left Analog Y
axis_angular_z: 2      # Right Analog Y
enable_button: 4       # L2 shoulder button
enable_turbo_button: 6 # L1 shoulder button
